# Create template for real line validation
print("=== PRIZEPICKS VALIDATION TEMPLATE ===")
print()
print("Collect 20 recent PrizePicks WNBA lines and compare:")
print()
print("Player | Stat | PP Line | Recent Avg | Difference | Your Pred")
print("-" * 60)
print("Example format:")
print("A'ja Wilson | PTS | 22.5 | 20.1 | +11.9% | UNDER")
print("Breanna Stewart | REB | 8.5 | 7.6 | +11.8% | UNDER") 
print("Sabrina Ionescu | AST | 6.5 | 5.8 | +12.1% | UNDER")
print()
print("If real PrizePicks lines are 8-15% above recent averages,")
print("this confirms your backtesting and validates the UNDER bias!")
print()
print("Quick validation check:")
print("1. Go to PrizePicks WNBA")
print("2. Pick 5-10 lines")
print("3. Check player's last 10-game average for that stat")
print("4. Calculate: (PP_Line - Recent_Avg) / Recent_Avg * 100")
print("5. If most lines are 8-15% above average → YOUR MODEL IS RIGHT")
