name: Check Secrets

on:
  workflow_dispatch:

jobs:
  check-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Check if secrets are set
        run: |
          echo "Checking secret lengths..."
          echo "DISCORD_WEBHOOK_URL length: ${#DISCORD_WEBHOOK_URL}"
          echo "SLACK_WEBHOOK_URL length: ${#SLACK_WEBHOOK_URL}"
          echo "TWILIO_SID length: ${#TWILIO_SID}"
          
          if [ -z "$DISCORD_WEBHOOK_URL" ]; then
            echo "❌ DISCORD_WEBHOOK_URL is empty!"
          else
            echo "✅ DISCORD_WEBHOOK_URL is set (${#DISCORD_WEBHOOK_URL} characters)"
          fi
          
          if [ -z "$SLACK_WEBHOOK_URL" ]; then
            echo "❌ SLACK_WEBHOOK_URL is empty!"
          else
            echo "✅ SLACK_WEBHOOK_URL is set (${#SLACK_WEBHOOK_URL} characters)"
          fi
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          TWILIO_SID: ${{ secrets.TWILIO_SID }}
