name: Dry Run

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run daily at 7:30 AM ET (11:30 UTC during EDT, 12:30 UTC during EST)
    - cron: '30 11 * * *'

jobs:
  dry-run:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Cache pip packages
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tests
      run: |
        pytest -v
    
    - name: Run auto_paper with line fetching
      run: |
        python scripts/auto_paper.py --fetch_lines
      env:
        PYTHONPATH: ${{ github.workspace }}
    
    - name: Upload predictions artifact
      uses: actions/upload-artifact@v3
      with:
        name: predictions
        path: predictions_*.csv
        retention-days: 7
    
    - name: Upload fetched lines artifact
      uses: actions/upload-artifact@v3
      with:
        name: prizepicks-lines
        path: data/prizepicks_lines_*.csv
        retention-days: 7