name: Dry Run

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'  # 8 AM ET daily

jobs:
  dry-run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up secrets
      env:
        GOOGLE_SA_JSON: ${{ secrets.GOOGLE_SA_JSON }}
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      run: |
        echo "$GOOGLE_SA_JSON" | base64 -d > credentials.json
        echo "DISCORD_WEBHOOK_URL=$DISCORD_WEBHOOK_URL" >> $GITHUB_ENV
        echo "SLACK_WEBHOOK_URL=$SLACK_WEBHOOK_URL" >> $GITHUB_ENV

    - name: Run auto paper trading
      run: |
        export PYTHONPATH="${PYTHONPATH}:${GITHUB_WORKSPACE}"
        python scripts/auto_paper.py --date today --dry_run

    - name: Check slip count
      run: |
        python -c "
        import csv
        with open('output/simulation_$(date +%Y-%m-%d).csv') as f:
            rows = list(csv.DictReader(f))
        print(f'Generated {len(rows)} slips')
        if len(rows) < 5:
            raise ValueError('Insufficient slips generated')
        "
