name: Dry Run

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'  # 8 AM ET daily

jobs:
  dry-run:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create mock environment
      run: |
        cat > .env << 'EOF'
        DISCORD_WEBHOOK_URL=mock-discord-webhook
        SLACK_WEBHOOK_URL=mock-slack-webhook
        TWILIO_SID=mock-twilio-sid
        TWILIO_AUTH=mock-twilio-auth
        TWILIO_FROM=+1234567890
        PHONE_TO=mock
        SHEET_ID=mock-sheet-id
        GOOGLE_SA_JSON=mock-google-json
        RESULTS_API_URL=mock-api-url
        EOF
    
    - name: Run test slip generation (skip PrizePicks)
      run: |
        echo "Skipping PrizePicks API in CI - using test data"
        python generate_test_slips.py
        
    - name: Check slip count
      run: |
        python -c "
        import json
        import glob
        files = glob.glob('paper_slips_*.json')
        if files:
            with open(files[0]) as f:
                data = json.load(f)
            print(f'Generated {len(data[\"slips\"])} test slips')
        "
        
    - name: Test alerts
      run: |
        python scripts/smoke_alert.py --discord --slack --sms || echo "Alerts in mock mode"
