name: Validate Secrets

on:
  workflow_dispatch:  # Manual trigger only
    inputs:
      verbose:
        description: 'Show detailed output'
        required: false
        default: 'false'

jobs:
  validate-secrets:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Check repository secrets
      run: |
        echo "🔍 Checking which secrets are available..."
        echo ""
        
        # Check Google Service Account
        if [ -n "${{ secrets.GOOGLE_SA_JSON }}" ]; then
          echo "✅ GOOGLE_SA_JSON: Set (length: ${#GOOGLE_SA_JSON} chars)"
          # Validate it's valid JSON
          echo "${{ secrets.GOOGLE_SA_JSON }}" | python -m json.tool > /dev/null 2>&1
          if [ $? -eq 0 ]; then
            echo "   ✅ Valid JSON format"
          else
            echo "   ❌ Invalid JSON format"
          fi
        else
          echo "❌ GOOGLE_SA_JSON: Not set"
        fi
        
        # Check Discord webhook
        if [ -n "${{ secrets.DISCORD_WEBHOOK_URL }}" ]; then
          DISCORD_MASKED="${{ secrets.DISCORD_WEBHOOK_URL }}"
          echo "✅ DISCORD_WEBHOOK_URL: ${DISCORD_MASKED:0:4}...${DISCORD_MASKED: -4}"
        else
          echo "❌ DISCORD_WEBHOOK_URL: Not set"
        fi
        
        # Check Slack webhook  
        if [ -n "${{ secrets.SLACK_WEBHOOK_URL }}" ]; then
          SLACK_MASKED="${{ secrets.SLACK_WEBHOOK_URL }}"
          echo "✅ SLACK_WEBHOOK_URL: ${SLACK_MASKED:0:4}...${SLACK_MASKED: -4}"
        else
          echo "❌ SLACK_WEBHOOK_URL: Not set"
        fi
        
        # Check Sheet ID
        if [ -n "${{ secrets.SHEET_ID }}" ]; then
          echo "✅ SHEET_ID: Set"
        else
          echo "⚠️  SHEET_ID: Not set (may be needed for sheets operations)"
        fi
        
        # Check Twilio secrets
        echo ""
        echo "📱 Twilio Secrets (for SMS):"
        [ -n "${{ secrets.TWILIO_SID }}" ] && echo "✅ TWILIO_SID: Set" || echo "⚠️  TWILIO_SID: Not set"
        [ -n "${{ secrets.TWILIO_AUTH }}" ] && echo "✅ TWILIO_AUTH: Set" || echo "⚠️  TWILIO_AUTH: Not set"
        [ -n "${{ secrets.TWILIO_FROM }}" ] && echo "✅ TWILIO_FROM: Set" || echo "⚠️  TWILIO_FROM: Not set"
        [ -n "${{ secrets.PHONE_TO }}" ] && echo "✅ PHONE_TO: Set" || echo "⚠️  PHONE_TO: Not set"
    
    - name: Test secret access in Python
      run: |
        python -c "
        import os
        import json
        
        print('\n🐍 Testing secret access from Python:')
        
        # Test GOOGLE_SA_JSON
        google_sa = os.environ.get('GOOGLE_SA_JSON', '')
        if google_sa:
            try:
                sa_data = json.loads(google_sa)
                print(f'✅ GOOGLE_SA_JSON: Valid JSON with project_id: {sa_data.get(\"project_id\", \"unknown\")}')
            except:
                print('❌ GOOGLE_SA_JSON: Present but invalid JSON')
        else:
            print('❌ GOOGLE_SA_JSON: Not accessible')
        
        # Test webhooks
        discord = os.environ.get('DISCORD_WEBHOOK_URL', '')
        slack = os.environ.get('SLACK_WEBHOOK_URL', '')
        
        print(f'✅ DISCORD_WEBHOOK_URL: {\"Set\" if discord else \"Not set\"}')
        print(f'✅ SLACK_WEBHOOK_URL: {\"Set\" if slack else \"Not set\"}')
        "
      env:
        GOOGLE_SA_JSON: ${{ secrets.GOOGLE_SA_JSON }}
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    
    - name: Summary
      run: |
        echo ""
        echo "📊 Summary:"
        echo "This workflow validates that GitHub secrets are properly configured."
        echo "All secrets marked with ✅ are ready for use in workflows."
        echo ""
        echo "Next steps:"
        echo "1. Run the dryrun.yml workflow to test Google Sheets integration"
        echo "2. Check Discord/Slack channels for test notifications"
