name: Test Without Secrets

on:
  workflow_dispatch:
  push:
    branches: [ main, fix/alert-finalization-merge ]

jobs:
  test-alerts:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create mock environment
      run: |
        # Create a mock .env file for testing
        cat > .env << 'EOF'
        DISCORD_WEBHOOK_URL=mock-discord-webhook
        SLACK_WEBHOOK_URL=mock-slack-webhook
        TWILIO_SID=mock-twilio-sid
        TWILIO_AUTH=mock-twilio-auth
        TWILIO_FROM=+1234567890
        PHONE_TO=mock
        SHEET_ID=mock-sheet-id
        GOOGLE_SA_JSON=mock-google-json
        RESULTS_API_URL=mock-api-url
        EOF
    
    - name: Test slip generation
      run: |
        python generate_test_slips.py
    
    - name: Test alerts in mock mode
      run: |
        python -c "
        from alerts.notifier import send_alert
        result = send_alert('GitHub Actions Test', 'Testing alerts in mock mode', {'Environment': 'CI', 'Mode': 'Mock'})
        print(f'Alert results: {result}')
        assert all(result.values()), 'Some alerts failed!'
        "
    
    - name: Run smoke tests
      run: |
        python scripts/smoke_alert.py --discord --slack --sms
