name: tests
on: [push, pull_request]
jobs:
  test:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.13"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Test Python directly
        run: |
          python -c "print('Python is working')"
          python -c "assert True; print('Assertions work')"
          python -c "import sys; print(f'Python version: {sys.version}')"
      - name: Test if file exists
        run: |
          python -c "import os; print(f'Current dir: {os.getcwd()}')"
          python -c "import os; print(f'Files: {os.listdir()}')"
          python -c "import os; print(f'Tests dir exists: {os.path.exists(\"tests\")}')"
      - name: Run test file directly
        run: python tests/test_dummy.py